### ISSUE TITLE
PHP notice

### ISSUE THREAD

**Issue by cut-media** [knub/wordbol#1] opened 2014-08-12 13:48 UTC
WP 3.9.2
PHP 5.4.26
Notice: Array to string conversion in /home/wp/public_html/wp-content/plugins/wordpress-stanbol/src/WordPressStanbol/AdminHtml.php on line 142

Also the closing ?> tag in wordpress-stanbol.php gives a fatal error
AND the zip file is named wordbol but the plugin is named wordpress-stanbol so if someone just unzips the plugin to wordbol it will not work, maybe add that to the readme?

**Comment by knub** [comment] 2014-08-20 20:45
Hi, thanks for the feedback.

Array to string conversion:
I can't see this error, and cannot understand it as well. In line 142, I reference $depictions_html, and this is a string. Can you give more details on how to reproduce?

Closing tag:
Could not reproduce, but I removed the closing tag as its good style anyways.

Plugin name:
I now renamed everything from wordpress-stanbol to wordbol, so there should be no reference to the wordpress-stanbol name anymore.

**Comment by cut-media** [comment] 2014-08-21 14:29
I saw the reference to $depictions_html which I think is the version of PHP, 5 treats arrays slightly different. Which are you using?
On Wordbol 1.1 now gives
Fatal error: Call to a member function getUri() on a non-object in /home/wp/public_html/wp-content/plugins/wordbol/src/Wordbol/StanbolEnhancer.php on line 62:
Investigating...

**Comment by knub** [comment] 2014-08-22 14:23
Hi,
I am using PHP 5.5.11.

I still do not understand the part about $depictions_html.
From the code, https://github.com/knub/wordbol/blob/master/src/Wordbol/AdminHtml.php#L92-L101, in $depictions_html clearly is a string, and only strings are appended. Hmm, strange ..

The error in StanbolEnhancer: When does it happen? When you activate the plugin? Or when trying to enhance post content?
Have you configured your Stanbol instance in config.php?

**Closed as completed** 2016-01-27 13:25 UTC
